ci: tf: fixup check

diff --git a/.github/workflows/check-terraform.yaml b/.github/workflows/check-terraform.yaml
--- a/.github/workflows/check-terraform.yaml
+++ b/.github/workflows/check-terraform.yaml
@@ -2,11 +2,6 @@ name: Check Terraform
 
 on:
   pull_request:
-    types:
-      - opened
-      - edited
-      - reopened
-      - synchronize
 
 defaults:
   run:
@@ -40,10 +35,12 @@ jobs:
     - name: Terraform Init
       id: init
       run: terraform init
+      continue-on-error: true
 
     - name: Terraform Validate
       id: validate
       run: terraform validate -no-color
+      continue-on-error: true
 
     - name: Place secret variables
       run: |
@@ -57,24 +54,79 @@ jobs:
       continue-on-error: true
 
     - uses: actions/github-script@v6
+      if: github.event_name == 'pull_request'
+      id: github-script
       env:
-        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+        FMT: "${{ steps.fmt.outputs.stdout }}"
+        INIT: "${{ steps.init.outputs.stderr }}"
+        VALIDATE: "${{ steps.validate.outputs.stderr }}"
       with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
+        result-encoding: string
         script: |
-          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-          <details><summary>Show Plan</summary>
-          \`\`\`\n
-          ${process.env.PLAN}
-          \`\`\`
-          </details>
-          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-          github.rest.issues.createComment({
-            issue_number: context.issue.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: output
-          })
+          let comment = `## Terraform Checks\n\n`;
+
+          if ("${{ steps.fmt.outcome }}" == "success") {
+            comment += `\n#### ✅ Terraform Format and Style Passed`;
+          } else {
+            // Split the output into an array of strings
+            let fileList = process.env.FMT.split("\n");
+            // Remove any empty lines from the array
+            fileList = fileList.filter((item) => item.trim() !== "");
+            fileList = fileList.map((item) => `<li><code>${item}</code></li>\n`);
+            filesString = fileList.join("\n");
+            comment += `\n#### ❌ Terraform Format and Style Failed
+          <details>
+          <summary>Failed Files</summary>
+          <ul>
+            ${filesString}
+          </ul>
+          </details>\n`;
+          }
+
+          if ("${{ steps.init.outcome }}" == "success") {
+            comment += `\n#### ✅ Terraform Initialization Passed`;
+          } else {
+            comment += `\n#### ❌ Terraform Initialization Failed
+          <details>
+          <summary><code>terraform init</code> output</summary>
+          <pre>\n
+          ${process.env.INIT}
+          </pre>\n
+          </details>\n`;
+          }
+
+          if ("${{ steps.validate.outcome }}" == "success") {
+            comment += `\n#### ✅ Terraform Validation Passed`;
+          } else {
+            comment += `\n#### ❌ Terraform Validation Failed
+          <details>
+          <summary><code>terraform validate</code> output</summary>
+          <pre>\n
+          ${process.env.VALIDATE}
+          </pre>\n
+          </details>`;
+          }
+
+          return comment;
+
+    - name: Find Comment
+      if: github.event_name == 'pull_request'
+      uses: peter-evans/find-comment@v2
+      id: fc
+      with:
+        comment-author: github-actions[bot]
+        issue-number: ${{ github.event.pull_request.number }}
+        body-includes: '## Terraform Checks'
+
+    - name: Create comment
+      if: github.event_name == 'pull_request'
+      uses: peter-evans/create-or-update-comment@v3
+      with:
+        comment-id: ${{ steps.fc.outputs.comment-id }}
+        edit-mode: replace
+        issue-number: ${{ github.event.pull_request.number }}
+        body: ${{ steps.github-script.outputs.result }}
+
+    - name: Error if failed
+      if: steps.fmt.outcome == 'failure' || steps.validate.outcome == 'failure' || steps.init.outcome == 'failure'
+      run: exit 1
